# Generated by Django 3.1.2 on 2020-10-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201021_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='order_type',
            field=models.CharField(choices=[(0, 'sale'), (1, 'purchase')], max_length=15),
        ),
    ]
